// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import AppJsx from "./components/App/App.jsx";

var make = AppJsx;

var App = {
  make: make
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(make, {}), root);
}

export {
  App ,
  
}
/* make Not a pure module */
